### ISSUE TITLE
doest work

### ISSUE THREAD

**Issue by kiran-coder-mx** [jashk/zion.dev#1]
hay que borrar estas lineas del archivo  puphpet/shell/install-puppet.sh
marca error al instalar las gems con esto omites la instalación
/opt/puppetlabs/puppet/bin/gem install deep_merge -v 1.0.1 --no-ri --no-rdoc
/opt/puppetlabs/puppet/bin/gem install activesupport -v 4.2.6 --no-ri --no-rdoc
/opt/puppetlabs/puppet/bin/gem install vine -v 0.2 --no-ri --no-rdoc

**Comment by jashk** [comment]
Hola, he visto el error otras veces como uno menor en la construcción de máquina. 

Puedes enviarme el log validar que sea eso.

**Comment by jashk** [comment]
Creo que te refieres a este problema en vagrant provision

`==> zion: ERROR:  Could not find a valid gem 'deep_merge' (= 1.0.1), here is why:
==> zion:           Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://rubygems.org/specs.4.8.gz)
==> zion: ERROR:  Could not find a valid gem 'activesupport' (= 4.2.6), here is why:
==> zion:           Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://rubygems.org/specs.4.8.gz)
==> zion: ERROR:  Could not find a valid gem 'vine' (= 0.2), here is why:
==> zion:           Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://rubygems.org/specs.4.8.gz)`
